/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.travelmate.managerBean.OrcamentoCurso.comparativo;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;

import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import br.com.travelmate.facade.FtpDadosFacade;
import br.com.travelmate.model.Ftpdados;
import br.com.travelmate.util.Ftp;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Kamila
 */
public class GerarEmailComparativo {

	private List<OrcamentoComparativoBean> listaOrcamento;

	public GerarEmailComparativo(List<OrcamentoComparativoBean> listaOrcamento) {
		this.listaOrcamento = listaOrcamento;
	}

	public void gerarRelatorioDSFile(String nomeArquivo) throws JRException, IOException, SQLException {
		FacesContext facesContext = FacesContext.getCurrentInstance();
		ServletContext servletContext = (ServletContext) facesContext.getExternalContext().getContext();
		String nomeFtp = nomeArquivo;
		nomeArquivo = servletContext.getRealPath("/orcamento/" + nomeArquivo);
		FileWriter arquivoHTML = new FileWriter(new File(nomeArquivo));
		if (listaOrcamento.size() == 2) {
			arquivoHTML.write(gerarArquivo2());
		} else
			arquivoHTML.write(gerarArquivo3());
		arquivoHTML.close();
		FtpDadosFacade ftpDadosFacade = new FtpDadosFacade();
		Ftpdados dadosFTP = null;
		dadosFTP = ftpDadosFacade.getFTPDados();
		Ftp ftp = new Ftp(dadosFTP.getHostupload(), dadosFTP.getUser(), dadosFTP.getPassword());
		ftp.conectar();
		File fileHTML = new File(nomeArquivo);
		ftp.enviarArquivo(fileHTML, nomeFtp, "/systm/orcamento/");
		ftp.desconectar();
	}

	public String gerarArquivo3() {
		String retorno = "<!DOCTYPE html>\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" style=\"background: #ffffff;\">\n" + "<head>\n"
				+ "<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\"/>\n"
				+ "<title>Relatório Comparativo</title>\n" + "<link\n"
				+ "	href=\"https://systm.com.br:82/systm/elementosOrcamento/cssOrcamentoComparativo.css\"\n"
				+ "	rel=\"stylesheet\" type=\"text/css\" media=\"print\" />\n" + "<link\n"
				+ "	href=\"https://systm.com.br:82/systm/elementosOrcamento/cssOrcamentoComparativo.css\"\n"
				+ "	rel=\"stylesheet\" type=\"text/css\" />\n"  + "<link\n"
				+ "	href=\"https://systm.com.br:82/systm/elementosOrcamento/bootstrap.min.css\"\n"
				+ "	rel=\"stylesheet\" />\n" + "<link\n"
				+ "	href=\"https://systm.com.br:82/systm/elementosOrcamento/bootstrap.min.css\"\n"
				+ "	rel=\"stylesheet\" media=\"print\" />\n" + "</head>\n" + "<body>\n"
				+ "	<form id=\"relatorioComparativo\" name=\"relatorioComparativo\"\n" + "		method=\"post\"\n"
				+ "		action=\"/systm_eclipse/pages/orcamento/relatorioOrcamentoComparativo.jsf\"\n"
				+ "		enctype=\"application/x-www-form-urlencoded\"\n" + "		style=\"background: #ffffff;\">\n"
				+ "		<input type=\"hidden\" name=\"relatorioComparativo\"\n"
				+ "			value=\"relatorioComparativo\" />\n" + "		<div align=\"center\">\n"
				+ "			<div style=\"width: 96%;\">\n"
				+ "				<table style=\"width: 100%; margin-bottom: -14px;\">\n" + "					<tbody>\n"
				+ "						<tr>\n"
				+ "							<td><table style=\"margin-bottom: -5px;\">\n"
				+ "									<tbody>\n" + "										<tr>\n"
				+ "											<td><img id=\"imgMate\"\n"
				+ "												src=\"https://systm.com.br:82/systm/elementosOrcamento/mate.png\"\n"
				+ "												width=\"40\" /></td>\n"
				+ "											<td><br /> <label id=\"relatorioComparativo:lblCliente\"\n"
				+ "												class=\"ui-outputlabel ui-widget\" style=\"font-size: 20px;\">Olá\n"
				+ "													"+listaOrcamento.get(0).getNomeCliente1()+"</label></td>\n"
				+ "										</tr>\n" + "									</tbody>\n"
				+ "								</table> <label id=\"relatorioComparativo:j_idt10\"\n"
				+ "								class=\"ui-outputlabel ui-widget\"\n"
				+ "								style=\"font-weight: 300; font-size: 13px;\">A Travelmate\n"
				+ "									busca proporcionar experiências pra vida toda.</label> <br /> <label\n"
				+ "								id=\"relatorioComparativo:j_idt12\"\n"
				+ "								class=\"ui-outputlabel ui-widget\"\n"
				+ "								style=\"font-weight: 300; font-size: 13px;\">Confira as\n"
				+ "									opções selecionadas e conte conosco para esclarecer suas\n"
				+ "									dúvidas, sempre com um atendimento personalizado.</label> <br /> <br />\n"
				+ "								<table style=\"margin-left: -0.5%;\">\n"
				+ "									<tbody>\n" + "										<tr>\n"
				+ "											<td><img id=\"imgOrcamento\"\n"
				+ "												src=\"https://systm.com.br:82/systm/elementosOrcamento/orcamento.png\" /></td>\n"
				+ "											<td><label id=\"relatorioComparativo:j_idt16\"\n"
				+ "												class=\"ui-outputlabel ui-widget\" style=\"font-size: 23px;\">CURSO\n"
				+ "													DE IDIOMAS</label></td>\n"
				+ "										</tr>\n" + "									</tbody>\n"
				+ "								</table></td>\n"
				+ "							<td><label id=\"relatorioComparativo:lblConsultor\"\n"
				+ "								class=\"ui-outputlabel ui-widget\"\n"
				+ "								style=\"font-weight: bold; font-size: 12px;\">"+listaOrcamento.get(0).getNomeConsultor1()+"\n"
				+ "									</label> <br /> <label id=\"relatorioComparativo:lblUnidade\"\n"
				+ "								style=\"font-style: italic; font-size: 13px;\">Consultor\n"
				+ "									em Intercâmbio | TravelMate "+listaOrcamento.get(0).getCidadeUnidade1()+"</label> <br /> <label\n"
				+ "								id=\"relatorioComparativo:lblEmailFone\"\n"
				+ "								style=\"font-style: italic; font-size: 13px;\">"+listaOrcamento.get(0).getEmailConsultor1()+"\n"
				+ "									| "+listaOrcamento.get(0).getFoneUnidade1()+"</label> <br /> <img id=\"imgLogoTM\"\n"
				+ "								src=\"https://systm.com.br:82/systm/elementosOrcamento/logoRelatorio.jpg\"\n"
				+ "								width=\"160\" style=\"margin-left: -5.8%;\" /></td>\n"
				+ "						</tr>\n" + "					</tbody>\n" + "				</table> \n"
				+ "				<hr class=\"linhaOrcamento\" />\n" + "				<div class=\"row\">\n";
		for (int i = 0; i < listaOrcamento.size(); i++) {
			retorno = retorno + "<div class=\"col-md-4\">\n"
					+"						<div align=\"center\" class=\"coresFundoOrcamento\">\n"
					+"							<div align=\"left\" style=\"width: 95%;\">\n"
					+"								<table style=\"margin-left: -0.5%; margin-bottom: -9px;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td><img id=\"imgIcon\"\n"
					+"												src=\"https://systm.com.br:82/systm/elementosOrcamento/iconCinza.png\" /></td>\n"
					+"											<td><label id=\"relatorioComparativo:j_idt23:0:j_idt29\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 12px;\">ORÇAMENTO\n"
					+"													"+listaOrcamento.get(i).getNumeroorcamento1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n" 
					+"								<hr class=\"linhaOrcamento\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt32\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Local</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt33\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getLocalCurso1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; border-top: 1px solid #4F4F4F;\n"
					+"  									margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt36\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Instituição\n"
					+"													de ensino</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt37\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getInstituicao1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt40\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Tipo de\n"
					+"													Curso</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt41\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getTipoCurso1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt44\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Data de\n"
					+"													Início</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt45\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getDataInicio1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n" 
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt48\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Data de\n"
					+"													Término</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt49\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getDataTermino1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt52\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Duração\n"
					+"													do Curso</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt53\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getDuracao1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt56\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Carga\n"
					+"													Horária</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt57\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getCargahoraria1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n" 
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt60\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Turno</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt61\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getTurno1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n" 
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-top: 5px; border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt64\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 12px;\">VALOR\n"
					+"													TOTAL</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt66\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 12px;\">"+listaOrcamento.get(i).getTotalCursome1()+"</label><label id=\"relatorioComparativo:j_idt23:0:j_idt67\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; margin-left: 2%;\">|</label><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt68\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 12px; margin-left: 2%;\">"+listaOrcamento.get(i).getTotalcursors1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n"
					+"								<div id=\"relatorioComparativo:tabelaProdutos\" align=\"left\"\n"
					+"									style=\"width: 100%;\">\n"
					+"									<div align=\"left\" style=\"width: 95%;\">\n"
					+"										<ul style=\"width: 113%; margin-left: -40px;\">\n";
			List<ProdutosOrcamentoComparativoBean> listaGrupos = listaOrcamento.get(i).getListaProdutos();
			for (int j = 0; j < listaGrupos.size(); j++) {
				if (listaGrupos.get(j).getListaProdutosOrcamento() != null
						&& listaGrupos.get(j).getListaProdutosOrcamento().size() > 0) {
					retorno = retorno +"<li style=\"list-style: none;\">\n"
							+"              <table\n"
							+"					style=\"margin-left: -0.5%; margin-bottom: -9px;\">\n"
							+"					<tbody>\n"
							+"						<tr>\n"
							+"							<td><img id=\"imgIcon\"\n"
							+"									src=\"https://systm.com.br:82/systm/elementosOrcamento/iconCinza.png\" /></td>\n"
							+"							<td><label\n"
							+"								id=\"relatorioComparativo:j_idt23:0:tabelaProdutos:0:j_idt71\"\n"
							+"								class=\"ui-outputlabel ui-widget\"\n"
							+"								style=\"font-weight: bold; font-size: 12px;\">"+listaGrupos.get(j).getTituloLista()+"</label></td>\n"
							+"						</tr>\n"
							+"					</tbody>\n"
							+"				</table> \n"
							+"				<hr class=\"linhaOrcamento\" />\n"
							+"			    <div style=\"margin-top: -16px;\">\n"
							+"					<div\n"
							+"						class=\"ui-datascroller-content ui-widget-content ui-corner-all\">\n"
							+"						<ul style=\"width: 107%; margin-left: -40px;\">\n";
					List<ListaProdutosOrcamentoComparativoBean> listaProdutos = listaGrupos.get(j)
							.getListaProdutosOrcamento();
					for (int j2 = 0; j2 < listaProdutos.size(); j2++) {
						retorno = retorno +"<li style=\"list-style: none;\"><table\n"
								+"					style=\"margin-bottom: -8px; width: 100%;\">\n"
								+"					<tbody>\n"
								+"						<tr>\n"
								+"							<td class=\"tamanho50\"><label\n" 
								+"								style=\"font-weight: bold; font-size: 11px;\">"+listaProdutos.get(j2).getDescricaolista()+"</label></td>\n"
								+"							<td class=\"tamanho50rig\"><label\n" 
								+"								style=\"font-weight: bold; font-size: 11px;\">"+listaProdutos.get(j2).getValorme()+"</label><label\n" 
								+"								style=\"font-weight: bold; font-size: 11px; margin-left: 2%;\">"+listaProdutos.get(j2).getValorrs()+"</label></td>\n"
								+"						</tr>\n"
								+"					</tbody>\n"
								+"				</table>\n"
								+"				<hr style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
								+"					border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
								+"</li>\n";
					}
					retorno = retorno +"						</ul>\n"
							+"					</div>\n"
							+"				</div>\n"
							+"<table style=\"width: 96.5%;\">\n"
							+"	<tbody>\n"
							+"		<tr>\n"
							+"			<td class=\"tamanho50\"><label\n" 
							+"				style=\"font-weight: bold; font-size: 12px;\">VALOR\n"
							+"					TOTAL</label></td>  \n"
							+"			<td class=\"tamanho50rig\"><label\n" 
							+"				style=\"font-weight: bold; font-size: 11px;\">"+listaGrupos.get(j).getTotalmelista()+"</label><label \n" 
							+"				style=\"font-weight: bold; margin-left: 2%;\">|</label><label\n" 
							+"				style=\"font-weight: bold; font-size: 12px; margin-left: 2%;\">"+listaGrupos.get(j).getTotalrslista()+"</label></td>\n"
							+"		</tr>\n"
							+"	</tbody>\n"
							+"</table>\n"
							+"	</li>\n";
				}
			}
			retorno = retorno + "										</ul>\n"
					+ "										<div class=\"ui-datascroller-loader\"></div>\n"
					+ "									</div>\n" + "								</div>\n"
					+ "								<div class=\"coresFundoValorOrcamento\" style=\"width: 105%;margin-left: -2.5%;\">\n"
					+ "									<label id=\"relatorioComparativo:j_idt23:0:j_idt80\"\n"
					+ "										class=\"ui-outputlabel ui-widget\">VALOR TOTAL DO \n"
					+ "										PACOTE*</label> <br /> <label\n"
					+ "										id=\"relatorioComparativo:j_idt23:0:j_idt82\"\n"
					+ "										class=\"ui-outputlabel ui-widget\">"+listaOrcamento.get(i).getSubPacoteme()+" | "+listaOrcamento.get(i).getSubPacoters()+"</label>\n"
					+ "								</div>\n" + "							</div>\n"
					+ "						</div>\n" + "					</div>  \n";
		}
		retorno = retorno + "				</div>\n" + "				<div align=\"left\">\n"
				+ "					<br /> <label id=\"relatorioComparativo:j_idt149\"\n"
				+ "						class=\"ui-outputlabel ui-widget\"\n"
				+ "						style=\"font-weight: 300; font-size: 13px;\">DATA DO\n"
				+ "						ORÇAMENTO: "+listaOrcamento.get(0).getDataOrcamento1()+"</label><label id=\"relatorioComparativo:j_idt150\"\n"
				+ "						class=\"ui-outputlabel ui-widget\"\n"
				+ "						style=\"margin-left: 2%; font-weight: 300; font-size: 13px;\">|</label><label\n"
				+ "						id=\"relatorioComparativo\"\n"
				+ "						style=\"margin-left: 2%; font-weight: 300; font-size: 13px;\">CÂMBIO\n"
				+ "						DO DIA: "+listaOrcamento.get(0).getCambio1()+"</label> <br /> <label id=\"relatorioComparativo\"\n"
				+ "						style=\"font-weight: 300; font-size: 13px;\">*Todos os\n"
				+ "						valores e condições de pagamento desse orçamento estão sujeitos a\n"
				+ "						alteração sem aviso prévio. Os valores e formas de pagamento são\n"
				+ "						válidos para o fechamento no dia de hoje - "+listaOrcamento.get(0).getDataOrcamento1()+"Consulte a\n"
				+ "						Travelmate para informações mais detalhadas sobre vistos,\n"
				+ "						documentação para viagens, vacinas, feriados locais e políticas de\n"
				+ "						alteração/cancelamento.</label> <br /> <br /> <br />\n"
				+ "				</div>\n" + "			</div>\n" + "		</div>\n" + "	</form>\n" + "</body>\n"
				+ "</html>\n";
		return retorno;
	}

	public String gerarArquivo2() {
		String retorno = "<!DOCTYPE html>\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" style=\"background: #ffffff;\">\n" + "<head>\n"
				+ "<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\"/>\n"
				+ "<title>Relatório Comparativo</title>\n" + "<link\n"
				+ "	href=\"https://systm.com.br:82/systm/elementosOrcamento/cssOrcamentoComparativo.css\"\n"
				+ "	rel=\"stylesheet\" type=\"text/css\" media=\"print\" />\n" + "<link\n"
				+ "	href=\"https://systm.com.br:82/systm/elementosOrcamento/cssOrcamentoComparativo.css\"\n"
				+ "	rel=\"stylesheet\" type=\"text/css\" />\n"  + "<link\n"
				+ "	href=\"https://systm.com.br:82/systm/elementosOrcamento/bootstrap.min.css\"\n"
				+ "	rel=\"stylesheet\" />\n" + "<link\n"
				+ "	href=\"https://systm.com.br:82/systm/elementosOrcamento/bootstrap.min.css\"\n"
				+ "	rel=\"stylesheet\" media=\"print\" />\n" + "</head>\n" + "<body>\n"
				+ "	<form id=\"relatorioComparativo\" name=\"relatorioComparativo\"\n" + "		method=\"post\"\n"
				+ "		action=\"/systm_eclipse/pages/orcamento/relatorioOrcamentoComparativo.jsf\"\n"
				+ "		enctype=\"application/x-www-form-urlencoded\"\n" + "		style=\"background: #ffffff;\">\n"
				+ "		<input type=\"hidden\" name=\"relatorioComparativo\"\n"
				+ "			value=\"relatorioComparativo\" />\n" + "		<div align=\"center\">\n"
				+ "			<div style=\"width: 96%;\">\n"
				+ "				<table style=\"width: 100%; margin-bottom: -14px;\">\n" + "					<tbody>\n"
				+ "						<tr>\n"
				+ "							<td><table style=\"margin-bottom: -5px;\">\n"
				+ "									<tbody>\n" + "										<tr>\n"
				+ "											<td><img id=\"imgMate\"\n"
				+ "												src=\"https://systm.com.br:82/systm/elementosOrcamento/mate.png\"\n"
				+ "												width=\"40\" /></td>\n"
				+ "											<td><br /> <label id=\"relatorioComparativo:lblCliente\"\n"
				+ "												class=\"ui-outputlabel ui-widget\" style=\"font-size: 20px;\">Olá\n"
				+ "													"+listaOrcamento.get(0).getNomeCliente1()+"</label></td>\n"
				+ "										</tr>\n" + "									</tbody>\n"
				+ "								</table> <label id=\"relatorioComparativo:j_idt10\"\n"
				+ "								class=\"ui-outputlabel ui-widget\"\n"
				+ "								style=\"font-weight: 300; font-size: 13px;\">A Travelmate\n"
				+ "									busca proporcionar experiências pra vida toda.</label> <br /> <label\n"
				+ "								id=\"relatorioComparativo:j_idt12\"\n"
				+ "								class=\"ui-outputlabel ui-widget\"\n"
				+ "								style=\"font-weight: 300; font-size: 13px;\">Confira as\n"
				+ "									opções selecionadas e conte conosco para esclarecer suas\n"
				+ "									dúvidas, sempre com um atendimento personalizado.</label> <br /> <br />\n"
				+ "								<table style=\"margin-left: -0.5%;\">\n"
				+ "									<tbody>\n" + "										<tr>\n"
				+ "											<td><img id=\"imgOrcamento\"\n"
				+ "												src=\"https://systm.com.br:82/systm/elementosOrcamento/orcamento.png\" /></td>\n"
				+ "											<td><label id=\"relatorioComparativo:j_idt16\"\n"
				+ "												class=\"ui-outputlabel ui-widget\" style=\"font-size: 23px;\">CURSO\n"
				+ "													DE IDIOMAS</label></td>\n"
				+ "										</tr>\n" + "									</tbody>\n"
				+ "								</table></td>\n"
				+ "							<td><label id=\"relatorioComparativo:lblConsultor\"\n"
				+ "								class=\"ui-outputlabel ui-widget\"\n"
				+ "								style=\"font-weight: bold; font-size: 12px;\">"+listaOrcamento.get(0).getNomeConsultor1()+"\n"
				+ "									</label> <br /> <label id=\"relatorioComparativo:lblUnidade\"\n"
				+ "								style=\"font-style: italic; font-size: 13px;\">Consultor\n"
				+ "									em Intercâmbio | TravelMate "+listaOrcamento.get(0).getCidadeUnidade1()+"</label> <br /> <label\n"
				+ "								id=\"relatorioComparativo:lblEmailFone\"\n"
				+ "								style=\"font-style: italic; font-size: 13px;\">"+listaOrcamento.get(0).getEmailConsultor1()+"\n"
				+ "									| "+listaOrcamento.get(0).getFoneUnidade1()+"</label> <br /> <img id=\"imgLogoTM\"\n"
				+ "								src=\"https://systm.com.br:82/systm/elementosOrcamento/logoRelatorio.jpg\"\n"
				+ "								width=\"160\" style=\"margin-left: -5.8%;\" /></td>\n"
				+ "						</tr>\n" + "					</tbody>\n" + "				</table> \n"
				+ "				<hr class=\"linhaOrcamento\" />\n" + "				<div class=\"row\">\n";
		for (int i = 0; i < listaOrcamento.size(); i++) {
			retorno = retorno + "<div class=\"col-md-6\">\n"
					+"						<div align=\"center\" class=\"coresFundoOrcamento\">\n"
					+"							<div align=\"left\" style=\"width: 95%;\">\n"
					+"								<table style=\"margin-left: -0.5%; margin-bottom: -9px;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td><img id=\"imgIcon\"\n"
					+"												src=\"https://systm.com.br:82/systm/elementosOrcamento/iconCinza.png\" /></td>\n"
					+"											<td><label id=\"relatorioComparativo:j_idt23:0:j_idt29\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 12px;\">ORÇAMENTO\n"
					+"													"+listaOrcamento.get(i).getNumeroorcamento1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n" 
					+"								<hr class=\"linhaOrcamento\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt32\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Local</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt33\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getLocalCurso1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; border-top: 1px solid #4F4F4F;\n"
					+"  									margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt36\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Instituição\n"
					+"													de ensino</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt37\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getInstituicao1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt40\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Tipo de\n"
					+"													Curso</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt41\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getTipoCurso1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt44\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Data de\n"
					+"													Início</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt45\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getDataInicio1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n" 
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt48\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Data de\n"
					+"													Término</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt49\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getDataTermino1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt52\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Duração\n"
					+"													do Curso</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt53\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getDuracao1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table> \n"
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt56\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Carga\n"
					+"													Horária</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt57\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getCargahoraria1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n" 
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
					+"									border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"margin-bottom: -8px; width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt60\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">Turno</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt61\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 11px;\">"+listaOrcamento.get(i).getTurno1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n" 
					+"								<hr\n"
					+"									style=\"color: #E0E0E0; background: #4F4F4F; margin-top: 5px; border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
					+"								<table style=\"width: 100%;\">\n"
					+"									<tbody>\n"
					+"										<tr>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt64\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 12px;\">VALOR\n"
					+"													TOTAL</label></td>\n"
					+"											<td class=\"tamanho50\"><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt66\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 12px;\">"+listaOrcamento.get(i).getTotalCursome1()+"</label><label id=\"relatorioComparativo:j_idt23:0:j_idt67\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; margin-left: 2%;\">|</label><label\n"
					+"												id=\"relatorioComparativo:j_idt23:0:j_idt68\"\n"
					+"												class=\"ui-outputlabel ui-widget\"\n"
					+"												style=\"font-weight: bold; font-size: 12px; margin-left: 2%;\">"+listaOrcamento.get(i).getTotalcursors1()+"</label></td>\n"
					+"										</tr>\n"
					+"									</tbody>\n"
					+"								</table>\n"
					+"								<div id=\"relatorioComparativo:tabelaProdutos\" align=\"left\"\n"
					+"									style=\"width: 100%;\">\n"
					+"									<div align=\"left\" style=\"width: 95%;\">\n"
					+"										<ul style=\"width: 113%; margin-left: -40px;\">\n";
			List<ProdutosOrcamentoComparativoBean> listaGrupos = listaOrcamento.get(i).getListaProdutos();
			for (int j = 0; j < listaGrupos.size(); j++) {
				if (listaGrupos.get(j).getListaProdutosOrcamento() != null
						&& listaGrupos.get(j).getListaProdutosOrcamento().size() > 0) {
					retorno = retorno +"<li style=\"list-style: none;\">\n"
							+"              <table\n"
							+"					style=\"margin-left: -0.5%; margin-bottom: -9px;\">\n"
							+"					<tbody>\n"
							+"						<tr>\n"
							+"							<td><img id=\"imgIcon\"\n"
							+"									src=\"https://systm.com.br:82/systm/elementosOrcamento/iconCinza.png\" /></td>\n"
							+"							<td><label\n"
							+"								id=\"relatorioComparativo:j_idt23:0:tabelaProdutos:0:j_idt71\"\n"
							+"								class=\"ui-outputlabel ui-widget\"\n"
							+"								style=\"font-weight: bold; font-size: 12px;\">"+listaGrupos.get(j).getTituloLista()+"</label></td>\n"
							+"						</tr>\n"
							+"					</tbody>\n"
							+"				</table> \n"
							+"				<hr class=\"linhaOrcamento\" />\n"
							+"			    <div style=\"margin-top: -16px;\">\n"
							+"					<div\n"
							+"						class=\"ui-datascroller-content ui-widget-content ui-corner-all\">\n"
							+"						<ul style=\"width: 107%; margin-left: -40px;\">\n";
					List<ListaProdutosOrcamentoComparativoBean> listaProdutos = listaGrupos.get(j)
							.getListaProdutosOrcamento();
					for (int j2 = 0; j2 < listaProdutos.size(); j2++) {
						retorno = retorno +"<li style=\"list-style: none;\"><table\n"
								+"					style=\"margin-bottom: -8px; width: 100%;\">\n"
								+"					<tbody>\n"
								+"						<tr>\n"
								+"							<td class=\"tamanho50\"><label\n" 
								+"								style=\"font-weight: bold; font-size: 11px;\">"+listaProdutos.get(j2).getDescricaolista()+"</label></td>\n"
								+"							<td class=\"tamanho50rig\"><label\n" 
								+"								style=\"font-weight: bold; font-size: 11px;\">"+listaProdutos.get(j2).getValorme()+"</label><label\n" 
								+"								style=\"font-weight: bold; font-size: 11px; margin-left: 2%;\">"+listaProdutos.get(j2).getValorrs()+"</label></td>\n"
								+"						</tr>\n"
								+"					</tbody>\n"
								+"				</table>\n"
								+"				<hr style=\"color: #E0E0E0; background: #4F4F4F; margin-bottom: -1px; margin-top: 5px; \n"
								+"					border-top: 1px solid #4F4F4F; margin-bottom: 2px;\" />\n"
								+"</li>\n";
					}
					retorno = retorno +"						</ul>\n"
							+"					</div>\n"
							+"				</div>\n"
							+"<table style=\"width: 100.3%;\">\n"
							+"	<tbody>\n"
							+"		<tr>\n"
							+"			<td class=\"tamanho50\"><label\n" 
							+"				style=\"font-weight: bold; font-size: 12px;\">VALOR\n"
							+"					TOTAL</label></td>  \n"
							+"			<td class=\"tamanho50rig\"><label\n" 
							+"				style=\"font-weight: bold; font-size: 11px;\">"+listaGrupos.get(j).getTotalmelista()+"</label><label \n" 
							+"				style=\"font-weight: bold; margin-left: 2%;\">|</label><label\n" 
							+"				style=\"font-weight: bold; font-size: 12px; margin-left: 2%;\">"+listaGrupos.get(j).getTotalrslista()+"</label></td>\n"
							+"		</tr>\n"
							+"	</tbody>\n"
							+"</table>\n"
							+"	</li>\n";
				}
			}
			retorno = retorno + "										</ul>\n"
					+ "										<div class=\"ui-datascroller-loader\"></div>\n"
					+ "									</div>\n" + "								</div>\n"
					+ "								<div class=\"coresFundoValorOrcamento\" style=\"width: 105%;margin-left: -2.5%;\">\n"
					+ "									<label id=\"relatorioComparativo:j_idt23:0:j_idt80\"\n"
					+ "										class=\"ui-outputlabel ui-widget\">VALOR TOTAL DO \n"
					+ "										PACOTE*</label> <br /> <label\n"
					+ "										id=\"relatorioComparativo:j_idt23:0:j_idt82\"\n"
					+ "										class=\"ui-outputlabel ui-widget\">"+listaOrcamento.get(i).getSubPacoteme()+" | "+listaOrcamento.get(i).getSubPacoters()+"</label>\n"
					+ "								</div>\n" + "							</div>\n"
					+ "						</div>\n" + "					</div>  \n";
		}
		retorno = retorno + "				</div>\n" + "				<div align=\"left\">\n"
				+ "					<br /> <label id=\"relatorioComparativo:j_idt149\"\n"
				+ "						class=\"ui-outputlabel ui-widget\"\n"
				+ "						style=\"font-weight: 300; font-size: 13px;\">DATA DO\n"
				+ "						ORÇAMENTO: "+listaOrcamento.get(0).getDataOrcamento1()+"</label><label id=\"relatorioComparativo:j_idt150\"\n"
				+ "						class=\"ui-outputlabel ui-widget\"\n"
				+ "						style=\"margin-left: 2%; font-weight: 300; font-size: 13px;\">|</label><label\n"
				+ "						id=\"relatorioComparativo\"\n"
				+ "						style=\"margin-left: 2%; font-weight: 300; font-size: 13px;\">CÂMBIO\n"
				+ "						DO DIA: "+listaOrcamento.get(0).getCambio1()+"</label> <br /> <label id=\"relatorioComparativo\"\n"
				+ "						style=\"font-weight: 300; font-size: 13px;\">*Todos os\n"
				+ "						valores e condições de pagamento desse orçamento estão sujeitos a\n"
				+ "						alteração sem aviso prévio. Os valores e formas de pagamento são\n"
				+ "						válidos para o fechamento no dia de hoje - "+listaOrcamento.get(0).getDataOrcamento1()+"Consulte a\n"
				+ "						Travelmate para informações mais detalhadas sobre vistos,\n"
				+ "						documentação para viagens, vacinas, feriados locais e políticas de\n"
				+ "						alteração/cancelamento.</label> <br /> <br /> <br />\n"
				+ "				</div>\n" + "			</div>\n" + "		</div>\n" + "	</form>\n" + "</body>\n"
				+ "</html>\n";
		return retorno;
	}

}
